### PR TITLE
Link in readme to an install guide 

### PR DESCRIPTION
**Pull request by exx8**
I know that for the developer of KASAN it's clear that you need to build the kernel for KASAN to work. But I believe a full guide can be helpful, for those who are new to KASAN.

This PR adds a link to  a full guide that clarify how to build kernel with KASAN.
solves #172

### CODE REVIEW

**Comment by exx8** [comment]
@googlebot I signed it!

**Comment by ramosian-glider** [comment]
I think it is pretty clear from https://www.kernel.org/doc/html/latest/dev-tools/kasan.html (referenced just below the part you are changing) that one must build the kernel in order for CONFIG_KASAN to take effect.
There are many online instructions on how to build the kernel, and someone wanting to fix bugs in it will be probably able to find one.

**Comment by exx8** [comment]
> I think it is pretty clear from https://www.kernel.org/doc/html/latest/dev-tools/kasan.html (referenced just below the part you are changing) that one must build the kernel in order for CONFIG_KASAN to take effect.
> There are many online instructions on how to build the kernel, and someone wanting to fix bugs in it will be probably able to find one.

see:
https://unix.stackexchange.com/questions/580865/how-do-i-enable-a-configuration-in-a-kernel

KASAN is a must for a Linux kernel module programmer. Because, it's a bit exotic, probably there are large number of one time kernel module writers.
Currently, it is not clear from the instructions that you need to rebuild the kernel with this option, nor how to do this. This PR tries, to make the first time, a bit easier.

**Comment by dvyukov** [comment]
KASAN is now upstream and docs are maintained upstream. The README page specifically only provides a few key references. If there is something missing in the upstream doc or they can be improved, I think the improvements should go there:
https://www.kernel.org/doc/html/latest/dev-tools/kasan.html
We don't want any active development/maintenance on the github page. Perhaps we need to reduce the docs even more to make it clearer that this is just a stub?

**Comment by xairy** [comment]
> KASAN is now upstream and docs are maintained upstream. The README page specifically only provides a few key references. If there is something missing in the upstream doc or they can be improved, I think the improvements should go there:
> https://www.kernel.org/doc/html/latest/dev-tools/kasan.html
> We don't want any active development/maintenance on the github page. Perhaps we need to reduce the docs even more to make it clearer that this is just a stub?

Done: https://github.com/google/kasan/commit/c0f2681e7d9371caede2458dbb9fe6fa7ac8a0ab

**Pull request closed without merging**
